-- Real-database edge cases for catalog generation (PostgreSQL 18). Loaded into a fresh database.
CREATE SCHEMA other;
CREATE TYPE other.shade AS ENUM ('light', 'dark');

CREATE SCHEMA edge_demo;
-- Extension-owned functions, types and views in the selected schema must not appear.
CREATE EXTENSION citext SCHEMA edge_demo;
CREATE EXTENSION pg_stat_statements SCHEMA edge_demo;
SET search_path = edge_demo, pg_catalog;

-- Types: one defined in the selected schema, one from another schema, one mixed case.
CREATE TYPE "Mood" AS ENUM ('sad', 'ok', 'happy');
CREATE TYPE tone AS ENUM ('b', 'a');
ALTER TYPE tone ADD VALUE 'c' BEFORE 'b';

-- Another schema's table uses a type from the selected schema (it renders qualified there).
CREATE TABLE other.consumers (tone edge_demo.tone, shade other.shade);

-- A quoted, mixed-case table whose key columns are mixed case too.
CREATE TABLE "Order Items" (
  "Id" bigint PRIMARY KEY,
  "Parent Id" bigint REFERENCES "Order Items" ("Id") ON DELETE SET NULL ON UPDATE CASCADE,
  mood "Mood" NOT NULL,
  moods "Mood"[] NOT NULL DEFAULT '{}',
  tone tone,
  tones tone[],
  shade other.shade,
  shades other.shade[],
  email citext,
  total integer GENERATED ALWAYS AS (length("Id"::text)) VIRTUAL,
  stored_total integer GENERATED ALWAYS AS (length("Id"::text)) STORED,
  ident integer GENERATED BY DEFAULT AS IDENTITY,
  note text NOT NULL CHECK (length(note) > 0),
  CONSTRAINT "Unique.Pair" UNIQUE ("Id", mood)
);
ALTER TABLE "Order Items" ADD CONSTRAINT "Odd.Check" CHECK ("Id" > 0) NOT VALID;
ALTER TABLE "Order Items" ADD CONSTRAINT "Loose Parent" FOREIGN KEY ("Parent Id", mood)
  REFERENCES "Order Items" ("Id", mood) NOT VALID;
COMMENT ON TABLE "Order Items" IS 'it''s quoted';
COMMENT ON COLUMN "Order Items".note IS 'a note';
CREATE INDEX "Mixed Index" ON "Order Items" (lower(note), "Parent Id" DESC);

-- A multi-level partitioned table: only the top-level parent is a catalog table. The index,
-- trigger and constraints cloned onto each leaf are not separate entries.
CREATE TABLE events (
  id bigint,
  created_at timestamptz NOT NULL,
  tenant text NOT NULL,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
CREATE INDEX events_tenant ON events (tenant);
CREATE TABLE events_2026 PARTITION OF events
  FOR VALUES FROM ('2026-01-01') TO ('2027-01-01') PARTITION BY RANGE (created_at);
CREATE TABLE events_2026_h1 PARTITION OF events_2026
  FOR VALUES FROM ('2026-01-01') TO ('2026-07-01');
CREATE FUNCTION touch() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
CREATE TRIGGER events_touch BEFORE UPDATE OF tenant ON events
  FOR EACH ROW EXECUTE FUNCTION touch();

-- A foreign key that references a partitioned table gets one extra constraint per partition.
CREATE TABLE event_refs (
  event_id bigint,
  event_at timestamptz,
  FOREIGN KEY (event_id, event_at) REFERENCES events (id, created_at) ON DELETE CASCADE
);

-- A deferrable unique constraint creates an internal constraint trigger.
CREATE TABLE deferred (v integer UNIQUE DEFERRABLE INITIALLY DEFERRED);

-- Function kinds and overloads: aggregates are out of scope, procedures are in.
CREATE FUNCTION over(a integer) RETURNS integer LANGUAGE sql AS 'SELECT a';
CREATE FUNCTION over(a text) RETURNS text LANGUAGE sql AS 'SELECT a';
CREATE FUNCTION over(a tone, b other.shade) RETURNS text LANGUAGE sql AS 'SELECT a::text';
CREATE PROCEDURE do_it(a integer) LANGUAGE sql AS 'SELECT a';
CREATE AGGREGATE sum_it(integer) (sfunc = int4pl, stype = integer, initcond = '0');

-- Views and materialized views, with comments.
CREATE VIEW order_items_v AS SELECT "Id" FROM "Order Items";
COMMENT ON VIEW order_items_v IS 'a view';
CREATE MATERIALIZED VIEW order_items_m AS SELECT "Id" FROM "Order Items";

-- Not catalog tables: a sequence, a foreign table, and objects added to an extension.
CREATE SEQUENCE plain_seq;
CREATE FOREIGN DATA WRAPPER dummy_wrapper;
CREATE SERVER dummy_server FOREIGN DATA WRAPPER dummy_wrapper;
CREATE FOREIGN TABLE foreign_things (id integer) SERVER dummy_server;
CREATE TABLE member_table (id integer);
CREATE VIEW member_view AS SELECT 1 AS one;
CREATE FUNCTION member_fn() RETURNS integer LANGUAGE sql AS 'SELECT 1';
CREATE TYPE member_enum AS ENUM ('x');
ALTER EXTENSION citext ADD TABLE member_table;
ALTER EXTENSION citext ADD VIEW member_view;
ALTER EXTENSION citext ADD FUNCTION member_fn();
ALTER EXTENSION citext ADD TYPE member_enum;
