projects:
  web:
    type: nextjs
    root: web

tests:
  playwright:
    frontendRoot: web/app
    navigationHelpers:
      - navigateTo
    selectors:
      testIds:
        - data-pw
      htmlIds: false
    selectorRoots:
      - web/app
      - web/components

test_plan:
  playwright:
    fullSuiteTriggers:
      projects: {}
    environments:
      prePush:
        groups:
          - type: direct
          - type: coverage
          - type: dependencies

rules: []
