name: CI

on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - id: filter
        with:
          filters: |
            backend:
              - "ts-shared/**"
              - "!ts-shared/utils/**"
