CREATE TABLE app."Accounts" (
 id uuid PRIMARY KEY,
 quoted "Uuid",
 qualified app."Money"[],
 matrix int[2][3],
 amount numeric(12,2) NOT NULL DEFAULT 0,
 sequence_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10),
 label text GENERATED ALWAYS AS (lower(quoted::text)) STORED,
 CONSTRAINT unique_amount UNIQUE (amount) DEFERRABLE INITIALLY DEFERRED,
 CONSTRAINT positive CHECK (amount >= 0),
 CONSTRAINT owner FOREIGN KEY (id) REFERENCES app.users(id) ON DELETE CASCADE ON UPDATE RESTRICT
);
ALTER TABLE app."Accounts" ADD COLUMN enabled boolean DEFAULT true,
 ALTER COLUMN quoted TYPE app."Uuid" USING quoted::app."Uuid",
 ALTER COLUMN amount SET DEFAULT 1,
 ALTER COLUMN amount DROP DEFAULT,
 ALTER COLUMN amount DROP NOT NULL,
 ALTER COLUMN amount SET NOT NULL,
 ADD CONSTRAINT valid CHECK (amount < 100) NOT VALID;
