#[test]
fn cli_parity_framework_parser_covers_all_public_values() {
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("dotnet").unwrap(),
        crate::tests::TestFramework::Dotnet
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("playwright").unwrap(),
        crate::tests::TestFramework::Playwright
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("swift").unwrap(),
        crate::tests::TestFramework::Swift
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("python").unwrap(),
        crate::tests::TestFramework::Python
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("go").unwrap(),
        crate::tests::TestFramework::Go
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("cargo").unwrap(),
        crate::tests::TestFramework::Cargo
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("rails").unwrap(),
        crate::tests::TestFramework::Rails
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("php").unwrap(),
        crate::tests::TestFramework::Php
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("java").unwrap(),
        crate::tests::TestFramework::Java
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("kotlin").unwrap(),
        crate::tests::TestFramework::Kotlin
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("elixir").unwrap(),
        crate::tests::TestFramework::Elixir
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("dart").unwrap(),
        crate::tests::TestFramework::Dart
    );
    assert_eq!(
        crate::napi_api::cli_parity::parse_test_framework("jest").unwrap(),
        crate::tests::TestFramework::Jest
    );
}
