name: Paths
on:
  push:
    paths:
      - "src/**"
      - "src/*.ts"
      - "!src/docs/**"
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - run: echo deploy
