import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const cjs = require("./index.js");

export const {
  analyzeProject,
  callSites,
  check,
  ciEnv,
  ciImpact,
  ciTopology,
  ciTopologyImpact,
  createWorkflowTopologyIndex,
  dataPw,
  deadExports,
  dependencies,
  dependents,
  effects,
  exportsOf,
  fetches,
  flow,
  impactedChecks,
  importUsages,
  importers,
  infraOutputs,
  infraResourceRefs,
  infraTestFor,
  lockfileDiff,
  playwrightCheck,
  playwrightEdges,
  playwrightRelated,
  playwrightTests,
  queueCheck,
  queueEdges,
  queueRelated,
  queues,
  reactAnalyze,
  reactCheck,
  reactUsages,
  registryExtension,
  related,
  resolveCheck,
  resolveConfig,
  rscCallers,
  serverContracts,
  serverRouteEdges,
  serverRouteList,
  serverRouteRelated,
  serverRoutes,
  swiftImporters,
  swiftTestTargets,
  symbols,
  testsComment,
  testsGraph,
  testsGraphMermaid,
  testsImpact,
  testsPlan,
  testsTargets,
  testsWhy,
  validateMermaidMarkdown,
  version,
  writePlanningImpactArtifacts,
} = cjs;

export default cjs;
