/** Which facts a generated catalog carries. It is stated in the catalog's `coverage` field. */
export type PostgresCatalogCoverage = "complete" | "ordering";
/** Explicit accessible relation names for requested schemas; an unrequested key is absent. */
export type PostgresSearchPathEvidence = Partial<Record<string, string[] | null>>;
export interface PostgresCatalogOptions {
  /** Environment variable containing a PostgreSQL connection URL; never pass secrets as options. */
  connectionEnv: string;
  /** Exact PostgreSQL schema name. */
  schema: string;
  /**
   * `complete` (the default) carries every schema fact, and every catalog rule accepts it.
   * `ordering` carries only what conflict and lock ordering need; other catalog rules reject it.
   */
  coverage?: PostgresCatalogCoverage;
  /** Opt in to evidence for these exact schemas; absent or inaccessible schemas become null. */
  searchPathSchemas?: string[];
}
export interface PostgresOrderingCatalog {
  formatVersion: 2;
  coverage: "ordering";
  schema: string;
  searchPathEvidence?: PostgresSearchPathEvidence;
  /** Exact connected database name; absent in catalogs generated by older versions. */
  currentDatabase?: string;
  tables: Record<string, PostgresCatalogTable>;
}
/** A catalog with every fact the catalog model holds. Every catalog rule accepts it. */
export interface PostgresCompleteCatalog {
  formatVersion: 2;
  coverage: "complete";
  schema: string;
  searchPathEvidence?: PostgresSearchPathEvidence;
  /** Exact connected database name; absent in catalogs generated by older versions. */
  currentDatabase?: string;
  tables: Record<string, PostgresCompleteCatalogTable>;
  functions: Record<string, PostgresCatalogFunction>;
  enums: Record<string, PostgresCatalogEnum>;
  views: Record<string, PostgresCatalogView>;
}
export type PostgresCatalog = PostgresOrderingCatalog | PostgresCompleteCatalog;
export interface PostgresCatalogColumn {
  dataType: string;
  nullable: boolean;
  ordinalPosition: number;
  defaultExpression: string | null;
  generated: "stored" | "virtual" | null;
  generatedExpression: string | null;
  identity: "a" | "d" | null;
}
export interface PostgresCompleteCatalogColumn extends PostgresCatalogColumn {
  comment: string | null;
}
export interface PostgresCatalogIndexKey {
  column: string | null;
  opclass: string;
  collation: string | null;
  orderingSupported: boolean;
  expression: string;
  descending: boolean;
  nullsFirst: boolean;
}
export interface PostgresCatalogIndex {
  accessMethod: string;
  unique: boolean;
  primary: boolean;
  constraintBacked: boolean;
  immediate: boolean;
  live: boolean;
  valid: boolean;
  ready: boolean;
  predicate: string | null;
  definition: string;
  keys: PostgresCatalogIndexKey[];
}
export interface PostgresCatalogTable {
  relationKind: "table" | "partitioned table";
  columns: Record<string, PostgresCatalogColumn>;
  primaryKey: { columns: string[] } | null;
  uniqueConstraints: Record<string, { columns: string[] }>;
  indexes: Record<string, PostgresCatalogIndex>;
}
export interface PostgresCatalogForeignKey {
  columns: string[];
  referencedTable: string;
  referencedColumns: string[];
  onDelete: "NO ACTION" | "RESTRICT" | "CASCADE" | "SET NULL" | "SET DEFAULT";
  onUpdate: "NO ACTION" | "RESTRICT" | "CASCADE" | "SET NULL" | "SET DEFAULT";
  validated: boolean;
}
export interface PostgresCompleteCatalogTable extends Omit<PostgresCatalogTable, "columns"> {
  columns: Record<string, PostgresCompleteCatalogColumn>;
  comment: string | null;
  /** `pg_get_partkeydef` text such as `RANGE (created_at)`; `null` unless partitioned. */
  physicalPartition: { key: string } | null;
  foreignKeys: Record<string, PostgresCatalogForeignKey>;
  /** `definition` is `pg_get_constraintdef` text; NOT NULL constraints are not checks. */
  checkConstraints: Record<string, { definition: string; validated: boolean }>;
  /** `definition` is `pg_get_triggerdef` text; internal triggers are omitted. */
  triggers: Record<string, { definition: string }>;
}
/** Keyed by name and identity arguments, such as `touch()` or `over(a integer)`. */
export interface PostgresCatalogFunction {
  /** `pg_get_functiondef` text. */
  definition: string;
}
export interface PostgresCatalogEnum {
  /** Labels in `enumsortorder`. */
  values: string[];
}
export interface PostgresCatalogView {
  materialized: boolean;
  /** `pg_get_viewdef` text. */
  definition: string;
  comment: string | null;
}
