projects:
  web:
    type: nextjs
    root: v2-app
tests:
  playwright:
    configs: playwright.v2.config.ts
    testInclude:
      - tests/**/*.spec.ts
    testExclude:
      - tests/flaky/**
    ignoreRoutes:
      - /ignored
    navigationHelpers:
      - navigateTo
    selectorInclude:
      - v2-components/**/*.tsx
    selectors:
      testIds:
        - data-v2
    selectorRoots:
      - v2-components
