#![cfg(test)]

//! Fixture-backed golden-JSON parity tests against the vendored TypeScript
//! engine, plus targeted unit tests for the trickiest pure logic
//! (Tarjan SCC, case-insensitive lookup, the expression scanner).
//!
//! Golden files (`expected*.json`) under `test-cases/workflow-topology/`
//! were generated by running the original engine's `loadWorkflowTopology` +
//! `renderWorkflowTopologyJson` directly (not its CLI, which writes nothing
//! to stdout when diagnostics are present — see its `runWorkflowTopologyCli`).
//! Regenerating a golden file after an intentional behavior change requires
//! the vendored TS source, which is not part of this repository; see the
//! PR/issue history for how it was produced.

mod artifact;

use super::case_insensitive_lookup::{CaseInsensitiveLookup, Resolution};
use super::expression_references::{
    static_references, static_workflow_output_references, workflow_output_references,
};
use super::graph_algorithms::strongly_connected_components;
use super::posix_path;
use super::render_json::render_workflow_topology_json;
use super::render_mermaid::render_workflow_topology_mermaid;
use super::topology_identifiers;
use super::{load_workflow_topology, model};
use crate::config::v2::schema::CiConfig;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};

fn fixture(name: &str) -> PathBuf {
    crate::codebase::ts_resolver::normalize_path(
        &PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../test-cases/workflow-topology")
            .join(name),
    )
}

fn golden(root: &Path, filename: &str) -> String {
    let path = root.join(filename);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()))
}

fn render(root: &Path, filters: &[&str]) -> String {
    let filters: Vec<String> = filters.iter().map(ToString::to_string).collect();
    let topology = load_workflow_topology(root, &CiConfig::default(), &filters);
    render_workflow_topology_json(&topology).expect("a parsed topology always serializes")
}

fn json(text: &str) -> serde_json::Value {
    serde_json::from_str(text).expect("golden and rendered output are both valid JSON")
}

fn render_mermaid(root: &Path) -> String {
    let topology = load_workflow_topology(root, &CiConfig::default(), &[]);
    render_workflow_topology_mermaid(&topology)
}

// ── Mermaid golden parity (workflow-run edges, remote calls, locks) ─────

#[test]
fn mermaid_matches_ts_engine_for_workflow_run_edges() {
    let root = fixture("workflow-run");
    assert_eq!(render_mermaid(&root), golden(&root, "expected.mmd"));
}

#[test]
fn mermaid_matches_ts_engine_for_local_and_remote_calls() {
    let root = fixture("reusable-calls");
    assert_eq!(render_mermaid(&root), golden(&root, "expected.mmd"));
}

/// Exercises the concurrency-lock rendering path specifically: a
/// workflow-level expression group (its own per-declaration lock) plus two
/// job-level literal groups differing only in case (sharing one lock,
/// since literal groups are keyed case-insensitively).
#[test]
fn mermaid_matches_ts_engine_for_concurrency_locks() {
    let root = fixture("concurrency");
    assert_eq!(render_mermaid(&root), golden(&root, "expected.mmd"));
    assert_eq!(render(&root, &[]), golden(&root, "expected.json"));
}

// ── golden-JSON parity against the TS engine ────────────────────────────

macro_rules! golden_test {
    ($name:ident, $fixture:expr) => {
        #[test]
        fn $name() {
            let root = fixture($fixture);
            assert_eq!(render(&root, &[]), golden(&root, "expected.json"));
        }
    };
}

golden_test!(needs_basic_matches_ts_engine, "needs-basic");
golden_test!(job_cycle_matches_ts_engine, "job-cycle");
golden_test!(step_references_matches_ts_engine, "step-references");
golden_test!(duplicate_names_matches_ts_engine, "duplicate-names");
golden_test!(reusable_calls_matches_ts_engine, "reusable-calls");
golden_test!(call_contracts_matches_ts_engine, "call-contracts");
golden_test!(workflow_run_matches_ts_engine, "workflow-run");
golden_test!(workflow_run_cycle_matches_ts_engine, "workflow-run-cycle");
golden_test!(
    workflow_run_chain_limit_matches_ts_engine,
    "workflow-run-chain-limit"
);

// ── artifact-dataflow golden parity ─────────────────────────────────────

golden_test!(artifact_basic_matches_ts_engine, "artifact-basic");
golden_test!(artifact_matrix_matches_ts_engine, "artifact-matrix");
golden_test!(artifact_certainty_matches_ts_engine, "artifact-certainty");
golden_test!(artifact_unresolved_matches_ts_engine, "artifact-unresolved");
golden_test!(
    artifact_diagnostics_matches_ts_engine,
    "artifact-diagnostics"
);
golden_test!(artifact_boundaries_matches_ts_engine, "artifact-boundaries");
golden_test!(
    artifact_resolution_limit_matches_ts_engine,
    "artifact-resolution-limit"
);

#[test]
fn workflow_filter_selects_transitive_local_callees() {
    let root = fixture("workflow-filters");
    assert_eq!(
        render(&root, &["root.yml"]),
        golden(&root, "expected-root.json")
    );
}

#[test]
fn workflow_filter_unknown_is_diagnosed() {
    let root = fixture("workflow-filters");
    assert_eq!(
        render(&root, &["unknown.yml"]),
        golden(&root, "expected-unknown.json")
    );
}

#[test]
fn workflow_filter_invalid_is_diagnosed() {
    let root = fixture("workflow-filters");
    assert_eq!(
        render(&root, &["../evil"]),
        golden(&root, "expected-invalid.json")
    );
}

/// `serde_yaml`'s and `js-yaml`'s parse-error messages are different
/// libraries' wording for the same malformed-YAML failure, so
/// `malformed-workflow`'s `message` text can never byte-match the TS
/// engine's. Every other field, and every other diagnostic in the same
/// fixture (including the dangling-needs case), still must.
#[test]
fn invalid_fixture_matches_ts_engine_except_malformed_message_text() {
    let root = fixture("invalid");
    let actual = strip_malformed_messages(json(&render(&root, &[])));
    let expected = strip_malformed_messages(json(&golden(&root, "expected.json")));
    assert_eq!(actual, expected);
}

fn strip_malformed_messages(mut value: serde_json::Value) -> serde_json::Value {
    if let Some(diagnostics) = value
        .get_mut("diagnostics")
        .and_then(serde_json::Value::as_array_mut)
    {
        for diagnostic in diagnostics {
            if diagnostic.get("code").and_then(serde_json::Value::as_str)
                == Some("malformed-workflow")
            {
                diagnostic["message"] = serde_json::Value::String("<parser-specific>".to_string());
            }
        }
    }
    value
}

// `ci.yml` in this fixture uses `actions/upload-artifact` /
// `actions/download-artifact` — this is the one golden fixture exercising
// the full pipeline end to end (needs/calls/workflow-run edges, every
// diagnostic kind, and same-run artifact dataflow) against the vendored
// TS engine's real output, byte for byte.
golden_test!(repository_matches_ts_engine, "repository");

// ── unit tests for pure logic (id helpers) ──────────────────────────────

#[test]
fn topology_identifiers_split_at_last_hash_boundary() {
    assert_eq!(
        topology_identifiers::workflow_path_from_id(".github/workflows/ci.yml"),
        ".github/workflows/ci.yml"
    );
    assert_eq!(
        topology_identifiers::workflow_path_from_id(".github/workflows/ci.yml#build"),
        ".github/workflows/ci.yml"
    );
}

// ── unit tests: graph_algorithms ────────────────────────────────────────

#[test]
fn scc_finds_a_cycle_and_leaves_isolated_nodes_singleton() {
    let mut adjacency: HashMap<String, HashSet<String>> = HashMap::new();
    adjacency.insert("a".into(), HashSet::from(["b".into()]));
    adjacency.insert("b".into(), HashSet::from(["c".into()]));
    adjacency.insert("c".into(), HashSet::from(["a".into()]));
    adjacency.insert("solo".into(), HashSet::new());

    let mut components = strongly_connected_components(&adjacency);
    components.sort();
    assert_eq!(
        components,
        vec![
            vec!["a".to_string(), "b".to_string(), "c".to_string()],
            vec!["solo".to_string()]
        ]
    );
}

#[test]
fn scc_visits_a_target_only_node_with_no_adjacency_entry() {
    // "b" is never a key in `adjacency`, only ever a target — the
    // algorithm must still visit it (with an implicit empty successor
    // set) rather than panicking or skipping it.
    let mut adjacency: HashMap<String, HashSet<String>> = HashMap::new();
    adjacency.insert("a".into(), HashSet::from(["b".into()]));

    let mut components = strongly_connected_components(&adjacency);
    components.sort();
    assert_eq!(
        components,
        vec![vec!["a".to_string()], vec!["b".to_string()]]
    );
}

// ── unit tests: case_insensitive_lookup ─────────────────────────────────

#[test]
fn case_insensitive_lookup_resolves_missing_ambiguous_and_resolved() {
    let lookup = CaseInsensitiveLookup::new([
        ("Build".to_string(), 1),
        ("build".to_string(), 2),
        ("Test".to_string(), 3),
    ]);

    assert!(matches!(lookup.resolve("nope"), Resolution::Missing));
    assert!(matches!(lookup.resolve("BUILD"), Resolution::Ambiguous));
    match lookup.resolve("test") {
        Resolution::Resolved { key, value } => {
            assert_eq!(key, "Test");
            assert_eq!(*value, 3);
        }
        Resolution::Missing => panic!("expected Resolved, got Missing"),
        Resolution::Ambiguous => panic!("expected Resolved, got Ambiguous"),
    }

    // Only the unambiguous "Test" entry survives into unique_entries().
    let unique: Vec<(&str, i32)> = lookup
        .unique_entries()
        .map(|(key, value)| (key, *value))
        .collect();
    assert_eq!(unique, vec![("Test", 3)]);
}

// ── unit tests: expression_references ───────────────────────────────────

#[test]
fn static_references_is_case_sensitive_and_ignores_quoted_text() {
    // Only the real `needs.` access counts; the quoted lookalike and the
    // differently-cased "Needs." do not.
    let refs = static_references(
        Some("needs.build.result == 'needs.fake' && Needs.other"),
        "needs",
    );
    assert_eq!(refs, vec!["build".to_string()]);
}

#[test]
fn static_references_supports_bracket_access() {
    let refs = static_references(Some("needs['build-job'].result == 'success'"), "needs");
    assert_eq!(refs, vec!["build-job".to_string()]);
}

#[test]
fn static_workflow_output_references_case_insensitive_needs_and_outputs() {
    let refs = static_workflow_output_references(Some("${{ NEEDS.Build.OUTPUTS.value }}"), false);
    assert_eq!(refs.len(), 1);
    assert_eq!(refs[0].call_job_id, "Build");
    assert_eq!(refs[0].output, "value");
}

#[test]
fn static_workflow_output_references_rejects_further_access() {
    // `needs.x.outputs.y.z` has trailing access past the output name, so
    // it isn't a bare output reference.
    let refs = static_workflow_output_references(Some("needs.build.outputs.value.nested"), true);
    assert!(refs.is_empty());
}

#[test]
fn static_workflow_output_references_allow_bare_toggles_delimiter_requirement() {
    let bare = "needs.build.outputs.value";
    assert!(static_workflow_output_references(Some(bare), false).is_empty());
    assert_eq!(static_workflow_output_references(Some(bare), true).len(), 1);
}

#[test]
fn workflow_output_references_scans_nested_scalars_and_bare_conditions() {
    let job: serde_yaml::Value = serde_yaml::from_str(
        r#"
if: needs.build.outputs.ready == 'true'
env:
  NESTED: "${{ needs.other.outputs.value }}"
steps:
  - if: needs.step-job.outputs.x == '1'
    run: echo hi
"#,
    )
    .unwrap();
    let mut refs: Vec<(String, String)> = workflow_output_references(&job)
        .into_iter()
        .map(|reference| (reference.call_job_id, reference.output))
        .collect();
    refs.sort();
    assert_eq!(
        refs,
        vec![
            ("build".to_string(), "ready".to_string()),
            ("other".to_string(), "value".to_string()),
            ("step-job".to_string(), "x".to_string()),
        ]
    );
}

// ── unit tests: posix_path ──────────────────────────────────────────────

#[test]
fn posix_normalize_resolves_dot_and_dot_dot_segments() {
    assert_eq!(
        posix_path::normalize(".github/workflows/./reusable.yml"),
        ".github/workflows/reusable.yml"
    );
    assert_eq!(
        posix_path::normalize(".github/workflows/../actions/reusable.yml"),
        ".github/actions/reusable.yml"
    );
    assert_eq!(posix_path::normalize("../outside.yml"), "../outside.yml");
    assert_eq!(posix_path::normalize(""), ".");
}

#[test]
fn posix_dirname_of_a_bare_basename_is_dot() {
    assert_eq!(
        posix_path::dirname(".github/workflows/ci.yml"),
        ".github/workflows"
    );
    assert_eq!(posix_path::dirname("ci.yml"), ".");
}

// ── model sanity: DiagnosticCode::as_str stays in sync with serde ───────

#[test]
fn diagnostic_code_as_str_matches_its_serde_wire_value() {
    for code in ALL_DIAGNOSTIC_CODES {
        let serialized = serde_json::to_value(code).unwrap();
        assert_eq!(
            serialized,
            serde_json::Value::String(code.as_str().to_string()),
            "{code:?}"
        );
    }
}

const ALL_DIAGNOSTIC_CODES: [model::DiagnosticCode; 25] = [
    model::DiagnosticCode::MalformedWorkflow,
    model::DiagnosticCode::MissingNeedsDependency,
    model::DiagnosticCode::JobDependencyCycle,
    model::DiagnosticCode::DuplicateStepId,
    model::DiagnosticCode::UnknownStepReference,
    model::DiagnosticCode::NonPriorStepReference,
    model::DiagnosticCode::DuplicateWorkflowName,
    model::DiagnosticCode::MissingLocalWorkflow,
    model::DiagnosticCode::NonCallableWorkflow,
    model::DiagnosticCode::WorkflowCallCycle,
    model::DiagnosticCode::MissingWorkflowRunSource,
    model::DiagnosticCode::AmbiguousWorkflowRunSource,
    model::DiagnosticCode::WorkflowRunCycle,
    model::DiagnosticCode::WorkflowRunChainLimit,
    model::DiagnosticCode::UnknownWorkflowFilter,
    model::DiagnosticCode::InvalidWorkflowFilter,
    model::DiagnosticCode::MissingWorkflowCallInput,
    model::DiagnosticCode::UnknownWorkflowCallInput,
    model::DiagnosticCode::WorkflowCallInputTypeMismatch,
    model::DiagnosticCode::MissingWorkflowCallSecret,
    model::DiagnosticCode::UnknownWorkflowCallSecret,
    model::DiagnosticCode::UnknownWorkflowCallOutput,
    model::DiagnosticCode::MissingArtifactProducer,
    model::DiagnosticCode::AmbiguousArtifactProducer,
    model::DiagnosticCode::ArtifactResolutionLimit,
];
