<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- This project intentionally opts out of SDK default compile items. -->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Shared.cs" Link="Shared.cs" />
  </ItemGroup>
</Project>
