CREATE TABLE orders (id int, updated_at int GENERATED ALWAYS AS (id + 1) STORED);
DROP TABLE orders;
ALTER TABLE IF EXISTS orders ADD COLUMN updated_at int GENERATED ALWAYS AS (1) STORED;
CREATE TABLE IF NOT EXISTS orders (id int, updated_at int);
ALTER TABLE IF EXISTS orders ADD COLUMN computed int GENERATED ALWAYS AS (id + 1) STORED;
ALTER TABLE IF EXISTS absent ADD COLUMN computed int GENERATED ALWAYS AS (1) STORED;
