import { query } from "@example/db";

// The catalog's `lower(email)` key is a text expression generated by real PostgreSQL.
export function addContacts(accountIds: string[], emails: string[]) {
  return query(
    `INSERT INTO contacts (account_id, email)
     SELECT input.account_id, input.email
     FROM unnest($1::uuid[], $2::text[]) AS input(account_id, email)
     ORDER BY input.account_id, lower(input.email), input.email
     ON CONFLICT (account_id, (lower(email))) DO NOTHING`,
    [accountIds, emails],
  );
}
