use super::support::{check, copy_tree, fixtures, Database};
use no_mistakes::codebase::postgres::SCHEMA_CATALOG_RULE_IDS;
use std::path::Path;

fn committed() -> std::path::PathBuf {
    fixtures().join("all-rules")
}

#[test]
fn generated_catalog_is_stable_and_matches_the_committed_fixture() {
    let Some(database) = Database::create("fixture") else {
        return;
    };
    database.load(&committed().join("schema.sql"));
    let version = database.query("SHOW server_version_num");
    assert!(
        version.starts_with("18"),
        "the committed catalog is generated by PostgreSQL 18, not {version:?}: deparse text \
         (pg_get_functiondef, pg_get_viewdef, pg_get_constraintdef, pg_get_triggerdef, \
         format_type) differs between major versions"
    );
    let first = database.catalog_bytes("catalog_demo", None);
    assert_eq!(
        first,
        database.catalog_bytes("catalog_demo", None),
        "generating twice from one database must be byte-identical"
    );
    let catalog: serde_json::Value = serde_json::from_slice(&first).unwrap();
    let current_database = database.query("SELECT current_database()");
    assert_eq!(
        catalog["currentDatabase"],
        current_database.trim(),
        "the catalog must record the connected database"
    );
    // Only the connected database varies across throwaway test runs. Remove its
    // exact generated line so the rest still compares byte-for-byte with the fixture.
    let text = String::from_utf8(first).unwrap();
    let database_field = format!(
        "  \"currentDatabase\": {},\n",
        serde_json::to_string(current_database.trim()).unwrap()
    );
    assert_eq!(text.matches(&database_field).count(), 1);
    let portable = text.replacen(&database_field, "", 1);
    for leaked in [current_database.trim(), "127.0.0.1", "server_version"] {
        assert!(
            !portable.contains(leaked),
            "the catalog must not name {leaked:?}"
        );
    }
    assert_eq!(
        portable.as_bytes(),
        std::fs::read(committed().join("schema.json")).unwrap(),
        "fixtures/postgres/catalog-generation/all-rules/schema.json drifted from schema.sql; \
         regenerate it with `no-mistakes postgres catalog --schema catalog_demo` on PostgreSQL 18"
    );
}

#[test]
fn every_catalog_rule_reports_a_finding_on_a_generated_catalog() {
    let Some(database) = Database::create("rules") else {
        return;
    };
    database.load(&committed().join("schema.sql"));
    let project = tempfile::tempdir().unwrap();
    copy_tree(&committed(), project.path());
    let output = database.generate(
        "catalog_demo",
        Some("complete"),
        &project.path().join("schema.json"),
    );
    assert!(output.status.success());
    let catalog: serde_json::Value =
        serde_json::from_slice(&std::fs::read(project.path().join("schema.json")).unwrap())
            .unwrap();
    assert_eq!(
        catalog["tables"]["nested_events_2026"]["relationKind"],
        "partitioned table"
    );
    assert_eq!(
        catalog["tables"]["nested_events_2026"]["partitionOf"],
        "nested_events"
    );
    assert!(catalog["tables"].get("nested_events_2026_a").is_none());
    assert_eq!(
        catalog["tables"]["local_key_leaf"]["partitionOf"],
        "partition_roots.local_key_parent"
    );
    assert!(catalog["tables"]["local_key_leaf"]["primaryKey"].is_null());
    assert!(catalog["tables"]["local_key_leaf"]["foreignKeys"]
        .get("local_key_leaf_account_fkey")
        .is_some());
    let (_, findings) = check(project.path(), &project.path().join(".no-mistakes.yml"));
    for rule in SCHEMA_CATALOG_RULE_IDS {
        let own: Vec<_> = findings.iter().filter(|(id, _, _)| id == rule).collect();
        assert!(!own.is_empty(), "{rule} reported nothing: {findings:#?}");
        assert!(
            own.iter().any(|(_, _, message)| !message.contains("stale")),
            "{rule} only reported stale allow entries"
        );
    }
    // `dataType` reaches the rules: the array column and the enum array are found by type.
    assert!(findings
        .iter()
        .any(|(id, _, message)| id == "postgres-array-columns"
            && message.contains("column:accounts.tags")
            && message.contains("(text[])")));
    assert!(findings
        .iter()
        .any(|(_, _, message)| message.contains("invoice_state[]")));
    assert!(findings.iter().any(|(id, _, message)| {
        id == "postgres-key-column-types"
            && message.contains("constraint:events.events_pkey")
            && message.contains("bigint column id")
    }));
    assert!(findings.iter().any(|(id, _, message)| {
        id == "postgres-key-column-types"
            && message.contains("constraint:nested_events_2026.nested_events_2026_pkey")
            && message.contains("bigint column id")
    }));
    assert!(!findings
        .iter()
        .any(|(_, _, message)| message.contains("nested_events_2026_a")));
    assert!(!findings.iter().any(|(id, _, message)| {
        id == "postgres-key-column-types" && message.contains("local_key_leaf")
    }));
}

#[test]
fn an_ordering_catalog_is_rejected_by_every_rule_that_needs_complete_facts() {
    let Some(database) = Database::create("ordering_rejected") else {
        return;
    };
    database.load(&committed().join("schema.sql"));
    let project = tempfile::tempdir().unwrap();
    copy_tree(&committed(), project.path());
    let output = database.generate(
        "catalog_demo",
        Some("ordering"),
        &project.path().join("schema.json"),
    );
    assert!(output.status.success());
    let config: serde_yaml::Value =
        serde_yaml::from_slice(&std::fs::read(committed().join(".no-mistakes.yml")).unwrap())
            .unwrap();
    for rule in SCHEMA_CATALOG_RULE_IDS {
        let single = serde_yaml::Mapping::from_iter([(
            "rules".into(),
            serde_yaml::Value::Sequence(
                config["rules"]
                    .as_sequence()
                    .unwrap()
                    .iter()
                    .filter(|entry| entry["rule"] == *rule)
                    .cloned()
                    .collect(),
            ),
        )]);
        let path = project.path().join(format!("{rule}.yml"));
        std::fs::write(&path, serde_yaml::to_string(&single).unwrap()).unwrap();
        let (output, findings) = check(Path::new(project.path()), &path);
        let stderr = String::from_utf8_lossy(&output.stderr);
        if matches!(
            *rule,
            "postgres-conflict-ordering" | "postgres-lock-ordering"
        ) {
            assert!(
                !stderr.contains("ordering-only coverage"),
                "{rule}: {stderr}"
            );
            assert!(!findings.is_empty(), "{rule} accepts the ordering catalog");
        } else {
            assert!(
                !output.status.success(),
                "{rule} accepted an ordering catalog"
            );
            assert!(
                stderr.contains("ordering-only coverage"),
                "{rule}: {stderr}"
            );
        }
    }
}
