CREATE TABLE orders (id int);
BEGIN;
DROP TABLE orders;
ROLLBACK;
BEGIN;
CREATE TABLE rolled_back_create (id int);
ALTER TABLE orders ADD COLUMN rolled_back_column int;
ROLLBACK;
START TRANSACTION;
CREATE TABLE committed_start (id int);
COMMIT;
BEGIN;
CREATE TABLE committed_end (id int);
END;
BEGIN;
CREATE TABLE aborted_create (id int);
ABORT;
BEGIN;
CREATE TABLE commit_prepared_is_not_commit (id int);
COMMIT PREPARED 'gid';
ROLLBACK;
BEGIN;
CREATE TABLE rollback_prepared_is_not_rollback (id int);
ROLLBACK PREPARED 'gid';
COMMIT;
BEGIN;
CREATE TABLE savepoint_kept (id int);
SAVEPOINT "Keep";
CREATE TABLE savepoint_removed (id int);
ROLLBACK WORK TO SAVEPOINT "Keep";
CREATE TABLE after_rollback_to (id int);
RELEASE SAVEPOINT "Keep";
COMMIT;
BEGIN;
SAVEPOINT without_keyword;
CREATE TABLE savepoint_without_keyword_removed (id int);
ROLLBACK TO without_keyword;
CREATE TABLE after_rollback_without_keyword (id int);
RELEASE SAVEPOINT without_keyword;
COMMIT;
BEGIN;
SAVEPOINT released;
CREATE TABLE released_then_rolled_back (id int);
RELEASE released;
ROLLBACK;
CREATE TEMP TABLE temporary_kept (id int);
DO $$ BEGIN
  CREATE TABLE plpgsql_block_kept (id int);
END $$;
