tests:
  playwright:
    configs: playwright.config.ts
rules:
  - name: playwright-no-set-timeout
    rule: forbidden-calls
    scope: repository
    options:
      roots:
        - playwright: true
      traversal: file
      unknownCalls: ignore
      targets:
        - global: setTimeout
        - exact: page.waitForTimeout
        - moduleExport:
            module: node:timers
            export: setTimeout
