filesystem:
  skipDirectories:
    - lib

projects:
  web:
    type: nextjs
    root: web

tests:
  playwright:
    configs: playwright.config.ts
    frontendRoot: web/app
    selectorRoots:
      - web/lib
    selectors:
      testIds:
        - data-testid

rules:
  - rule: playwright-coverage
    projects:
      - web
