name: Release
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: "release-${{ github.run_id }}"
      cancel-in-progress: false
      queue: max
    steps:
      - run: echo publish
