INSERT INTO orders (computed) VALUES (1) ON CONFLICT (id) DO UPDATE SET computed = 2;
UPDATE orders SET (id, computed) = (1, 2);
MERGE INTO orders USING source ON true WHEN MATCHED THEN UPDATE SET computed = 3 WHEN NOT MATCHED THEN INSERT (computed) VALUES (4);
MERGE INTO orders USING source ON true WHEN NOT MATCHED THEN INSERT VALUES (1, 2) WHEN MATCHED THEN DELETE;
SELECT 1;
