use sqlparser::keywords::Keyword;
use sqlparser::tokenizer::Token;

/// PostgreSQL reserved keywords that cannot be unquoted column names.
/// sqlparser's `is_reserved_for_identifier` is not this list: it omits `NULL`.
const RESERVED_COLUMN_NAME: &[Keyword] = &[
    Keyword::ALL,
    Keyword::AND,
    Keyword::ANY,
    Keyword::AS,
    Keyword::ASC,
    Keyword::CASE,
    Keyword::CAST,
    Keyword::CHECK,
    Keyword::COLLATE,
    Keyword::COLUMN,
    Keyword::CONSTRAINT,
    Keyword::CREATE,
    Keyword::DEFAULT,
    Keyword::DEFERRABLE,
    Keyword::DESC,
    Keyword::DISTINCT,
    Keyword::DO,
    Keyword::ELSE,
    Keyword::END,
    Keyword::EXCEPT,
    Keyword::FALSE,
    Keyword::FETCH,
    Keyword::FOR,
    Keyword::FOREIGN,
    Keyword::FROM,
    Keyword::GRANT,
    Keyword::GROUP,
    Keyword::HAVING,
    Keyword::IN,
    Keyword::INITIALLY,
    Keyword::INTERSECT,
    Keyword::INTO,
    Keyword::LATERAL,
    Keyword::LEADING,
    Keyword::LIMIT,
    Keyword::NOT,
    Keyword::NULL,
    Keyword::OFFSET,
    Keyword::ON,
    Keyword::ONLY,
    Keyword::OR,
    Keyword::ORDER,
    Keyword::PRIMARY,
    Keyword::REFERENCES,
    Keyword::RETURNING,
    Keyword::SELECT,
    Keyword::SOME,
    Keyword::TABLE,
    Keyword::THEN,
    Keyword::TO,
    Keyword::TRUE,
    Keyword::UNION,
    Keyword::UNIQUE,
    Keyword::USER,
    Keyword::USING,
    Keyword::WHEN,
    Keyword::WHERE,
    Keyword::WINDOW,
    Keyword::WITH,
];

pub(super) fn is_column_name(token: &Token) -> bool {
    match token {
        Token::Word(word) if word.quote_style.is_some() => true,
        Token::Word(word) => !RESERVED_COLUMN_NAME.contains(&word.keyword),
        _ => false,
    }
}
