name: CI

on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - "ts-shared/**"
              - "src/**/*.test.ts"
