projects:
  web:
    type: nextjs
    root: web

tests:
  playwright:
    configs: playwright.config.ts
    selectors:
      testIds:
        - data-testid

rules:
  - rule: playwright-unique-test-ids
    projects:
      - web
