name: GitHub Actions

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - ".github/actionlint.yml"
      - ".github/actionlint.yaml"
      - "actionlint.yml"
      - "actionlint.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"
      - ".github/actionlint.yml"
      - ".github/actionlint.yaml"
      - "actionlint.yml"
      - "actionlint.yaml"

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2
