name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # for OpenID Connect authentication with CodSpeed

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6190aa5fb88a88ee71c12769924bbe63a9ab152e # 1.96.0
        with:
          toolchain: "1.96.0"

      - name: Cache Rust build artifacts
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-targets: "false"

      - name: Install cargo-codspeed
        uses: taiki-e/install-action@4684b8405694ae9dd42c9f39ba901a70ae83f4a3 # v2.82.9
        with:
          tool: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build -p no-mistakes

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@4bee4eada46987d4607fc208971a36367352b83d # v4.18.5
        with:
          mode: simulation
          run: cargo codspeed run -p no-mistakes
