extern crate self as no_mistakes;

pub mod ast;
mod check_discovery;
mod check_parallel;
mod check_runner;
mod check_tasks;
pub mod ci;
pub mod cli;
pub mod codebase;
pub mod config;
pub mod data_pw_query;
pub mod effects_query;
pub mod fetch;
mod fetches;
pub mod flow_query;
pub mod impacted_checks;
pub mod import_shape;
pub mod imports;
pub mod integration_tests;
pub mod napi_api;
pub mod perf_trace;
pub mod playwright;
pub mod queue;
pub mod react_traits;
pub mod registry_extension_query;
pub mod routes;
pub mod rsc_callers_query;
pub mod server_routes;
pub mod swift_api;
pub mod terraform_api;
#[cfg(test)]
pub(crate) mod test_support;
mod tests;
pub use ci::{run as ci_run, CiArgs};
pub use impacted_checks::{run as impacted_checks_run, ImpactedChecksArgs};
pub use tests::{run as tests_run, TestsArgs};
